name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Check code coverage
        run: |
          wget https://github.com/fjacquet/jacoco-checker/releases/download/v1.0.0/jacoco-checker-1.0.0.jar
          java -jar jacoco-checker-1.0.0.jar --reportPath target/site/jacoco/jacoco.xml --limit 0.8